### ISSUE TITLE
[[wiki-links]]

### ISSUE THREAD

**Issue by erusev** [notaapp/roadmap#38]
support [[wiki-link]] syntax for linking between documents

**Comment by erusev** [comment]
done

**Comment by nianiam** [comment]
I appreciate this is closed, but seemed like a sensible place to comment.

Is there any particular reason that in preview mode the wiki-links still appear like [[Text]]? Surely the point of preview mode is to remove all of the markdown.

I think they should appear more like a normal link. Perhaps they could be a different text colour to differentiate from external links.

**Comment by erusev** [comment]
Thanks for the comment! We just fixed this in the development version and will ship the fix with the next release.
